---
title: "Assignment-1"
author: "Group 7"
date: "2/3/2020"
output:
  word_document: default
  html_document: default
---

```{r}

library(keras)
imdb <- dataset_imdb(num_words = 10000)# top 10,000 most frequently occurring words in the training data
c(c(train_data, train_labels), c(test_data, test_labels)) %<-% imdb
# Preparing Data
vectorize_sequences <- function(sequences, dimension = 10000) {
  # Create an all-zero matrix of shape (len(sequences), dimension)
  results <- matrix(0, nrow = length(sequences), ncol = dimension)
  for (i in 1:length(sequences))
    # Sets specific indices of results[i] to 1s
    results[i, sequences[[i]]] <- 1
  results
}
# Our vectorized training data
x_train <- vectorize_sequences(train_data)
# Our vectorized test data
x_test <- vectorize_sequences(test_data)
str(x_train[1,])
# Our vectorized labels
y_train <- as.numeric(train_labels)
y_test <- as.numeric(test_labels)
val_indices <- 1:10000
x_val <- x_train[val_indices,]
partial_x_train <- x_train[-val_indices,]
y_val <- y_train[val_indices]
partial_y_train <- y_train[-val_indices]

```

# 8 units
```{r}

# Using layers with 8 hidden units rather than 16 units

model <- keras_model_sequential() %>% 
  layer_dense(units = 8, activation = "relu",input_shape = c(10000)) %>% 
  layer_dense(units = 8, activation = "relu")%>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 3, batch_size = 512)
model %>% evaluate(x_test, y_test)

```

# 32 units
```{r}

# Using layers with 32 hidden units rather than 16 units

model <- keras_model_sequential() %>% 
  layer_dense(units = 32, activation = "relu",input_shape = c(10000)) %>% 
  layer_dense(units = 32, activation = "relu")%>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)

```

# 64 units
```{r}

# Using layers with 64 hidden units rather than 16 units

model <- keras_model_sequential() %>% 
  layer_dense(units = 64, activation = "relu",input_shape = c(10000)) %>% 
  layer_dense(units = 64, activation = "relu")%>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)

```

# Single Hidden Layer
```{r}

# Using one hidden layer

model <- keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu",input_shape = c(10000)) %>% 
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)

```

# Third Hidden Layer
```{r}

# Using three hidden layers 

model <- keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu",input_shape = c(10000)) %>% 
  layer_dense(units = 16, activation = "relu")%>%
  layer_dense(units = 16, activation = "relu")%>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)

```

# MSE (Mean Squared Error)
```{r}

# Using Loss Function "mse" 

model <- keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu",input_shape = c(10000)) %>% 
  layer_dense(units = 16, activation = "relu")%>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "mse",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)

```

# Tanh
```{r}

# Using "tanh" activation instead of "relu"

model <- keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "tanh",input_shape = c(10000)) %>% 
  layer_dense(units = 16, activation = "tanh")%>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)

```

# Regularization
```{r}

# Using Regularization technique for tuning the function by adding an additional penalty term in the error function.

model <- keras_model_sequential() %>% 
  layer_dense(units = 16, kernel_regularizer =  regularizer_l2(0.001), activation = "relu", input_shape = c(10000)) %>% 
  layer_dense(units = 16, kernel_regularizer =  regularizer_l2(0.001),activation = "relu") %>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)

```

# Drop-out
```{r}

# Using Drop-out technique which refers to dropping out units to prevent overfitting

model <- keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu", input_shape = c(10000)) %>% 
  layer_dropout(rate=0.5) %>%
  layer_dense(units = 16, activation = "relu") %>% 
  layer_dropout(rate=0.5) %>%
  layer_dense(units = 1, activation = "sigmoid")
model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))
str(history)
plot(history)
model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)

```
# Final Model Applying the used hypertuning parameters.

```{r}

model <- keras_model_sequential() %>% 
  layer_dense(units = 32, kernel_regularizer =  regularizer_l2(0.001), activation = "tanh", input_shape = c(10000)) %>%
  layer_dropout(rate=0.5) %>%
  layer_dense(units = 16, activation = "tanh", kernel_regularizer =  regularizer_l2(0.001)) %>%
  layer_dropout(rate=0.5) %>%
  layer_dense(units = 32, activation = "tanh",kernel_regularizer =  regularizer_l2(0.001)) %>%
  layer_dropout(rate=0.5) %>%
  layer_dense(units = 1, activation = "sigmoid")

model %>% compile(
  optimizer = "rmsprop",
  loss = "mse",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val))

plot(history)

model %>% fit(x_train, y_train, epochs = 2, batch_size = 512)
model %>% evaluate(x_test, y_test)
model %>% predict(x_test[1:10,])
```

Here we could find the minimum loss function with good accuracy.
